print("git clone \"HTTPS link\"")
print("git add \"file to add\"")
print("git status")
print("git commit -m \"commit\"")
print("git push")
print("git checkout -- file name/ . will undo all the files")
print("Delete")