print("git clone \"HTTPS link\"")
print("git add \"file to add\"")
print("git status")
print("git commit -m \"commit\"")
print("git push")
print("git checkout -- file name/ . will undo all the files")
print("git revert (-n will not commit chnages)commit_id")
print("git reset --hard commit_id(will take you back to the commit_id changes)")
print("git branch")
print("git branch test(for creating new branch)")
print("git checkout <branch_name>(to change branch)")
print("git checkout -b <branch_name>(for creating new branch and checkout parallely)")
print("git push origin --delete branch_name(to delete branch from remote repository)")
print("git branch -d branch_name ")
print("git show HEAD")
print("git difftool <older_commit> <new_commit>")
print("git difftool <older_commit> HEAD~1 HEAD")
print("git difftool <older_commit> HEAD~2 HEAD~1")
print("If we want to checkout diff branch but pointer is in different commit then this will detach head")
print("gitignore - if we want to ignor any file while commiting, create .gitignore file(touch .gitignore) and add that unwanted file name inside this file")
