print("git clone \"HTTPS link\"")
print("git add \"file to add\"")
print("git status")
print("git commit -m \"commit\"")
print("git push")
print("git checkout -- file name/ . will undo all the files")
print("git revert (-n will not commit chnages)commit_id")
print("git reset --hard commit_id(will take you back to the commit_id changes)")
print("git branch")
print("git branch test(for creating new branch)")
print("git checkout <branch_name>(to change branch)")
